services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      MANUAL: "Y"
  DISK_SIZE: "256G"
  RAM_SIZE: "16G"
  CPU_CORES: "8"
  ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234"
    devices:
      - /dev/kvm
      - /dev/bus/usb
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
